In [2]:
#install a library/module
import numpy as np

In [3]:
#numpy works with arrays and number calculation
#if want matrix calculations, need to convert array into matrix explicitly

In [5]:
my_list = [1,2,3]
my_list
#had to use underscore in name because . and - have predefined meanings

[1, 2, 3]

In [6]:
np.array(my_list)

array([1, 2, 3])

In [7]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
#arange
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#step by 2
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
#zeros()
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
#ones
np.ones(3)

array([1., 1., 1.])

In [16]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
#linspace()
#total of 3 numbers evenly spaced from 0 to 10
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [19]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [20]:
# eye()
#create an identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
# np.random()
# .rand attribute follows a uniform distribution
np.random.rand(2)

array([0.35559936, 0.02977848])

In [22]:
np.random.rand(5,5)

array([[0.75164037, 0.35264194, 0.21771783, 0.38634655, 0.68736815],
       [0.55368768, 0.58413458, 0.41625423, 0.76422503, 0.58694728],
       [0.76356023, 0.62357699, 0.71181304, 0.82519703, 0.53836733],
       [0.09547603, 0.74995574, 0.01673875, 0.62990339, 0.7640118 ],
       [0.39896638, 0.76732728, 0.67425264, 0.99959895, 0.31218694]])

In [23]:
#random integers from low (inclusive) to high (exclusive) range
#.randint attribute gives random integers
np.random.randint(1,100,10)

array([75, 57, 36, 69, 90,  8, 18, 24,  7, 32])

In [29]:
arr = np.arange(25)
ranarr = numpy.random.randint(0,50,10)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
ranarr

array([46, 41, 34, 12,  6, 11,  6, 25, 11, 41])

In [32]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
ranarr.max()

46

In [34]:
ranarr.argmax()

0

In [35]:
ranarr[5]

11

In [36]:
ranarr.min()

6

In [37]:
ranarr.argmin()

4

In [38]:
arr.shape

(25,)

In [39]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [40]:
arr.reshape(1,25).shape

(1, 25)

In [42]:
arr.reshape(25,1) 
#note this is not a permanant reshape unless redefine arr = arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [45]:
arr = arr.reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
numpy.mat(arr)
#.mat defines array as a matrix
# array must be defined as a matrix to be able to do matrix calculations

matrix([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])

In [48]:
arr.dtype
#note this is an attribute, not a method, therefore does not need parenthenses arr.dtype() no

dtype('int32')

In [49]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [50]:
arr = numpy.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [51]:
arr[8]

8

In [52]:
arr[1:5]
#lower end of range is included; top of range is excluded (end-1)

array([1, 2, 3, 4])

In [53]:
#broadcasting
arr[0:5] = 100
#in this case we do not need to redefine the array as arr = arr[0:5]; putting the = at the end still makes redefine
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [54]:
arr = np.arange(25)

In [55]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [57]:
#array slicing
slice_arr = arr[0:6]
#note that slice_arr is a "view" of arr array, not a new array
slice_arr
#note slice is a function, cannot use as name alone

array([0, 1, 2, 3, 4, 5])

In [58]:
slice_arr[:] = 99
slice_arr

array([99, 99, 99, 99, 99, 99])

In [59]:
arr
#note that this change in slice_arr (view) carried over into original arr array

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [62]:
#revert to original arr array
arr = np.arange(25)

In [63]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [60]:
#if you wanted a true COPY (not a view of original array)
arr_copy = arr[0:6].copy()
arr_copy

array([99, 99, 99, 99, 99, 99])

In [64]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [65]:
arr2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [66]:
numpy.arange(5,46,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [67]:
numpy.arange(5,45,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40])

In [68]:
numpy.arange(5,46,5).reshape(3,3)

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [69]:
arr2d[1]

array([20, 25, 30])

In [70]:
#first row
arr2d[0]

array([ 5, 10, 15])

In [71]:
#array[row,col]
#array[row][col] also works
arr2d[1,0]
#2nd row, 1st column

20

In [72]:
arr2d[:2,:2]
#everything up to but not including row 2
#everything up to but not incluing column 2

array([[ 5, 10],
       [20, 25]])

In [73]:
arr2d[2]
#bottom row

array([35, 40, 45])

In [75]:
arr2d[:,2]
#last column

array([15, 30, 45])

In [76]:
#fancy indexing
arr3d = numpy.arange(1,101).reshape(10,10)
arr3d

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [78]:
arr3d[[0,2,4,6,8]]
#gives odd rows

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [81, 82, 83, 84, 85, 86, 87, 88, 89, 90]])

In [80]:
arr3d[[1,7,3,2,8]]
#slice specified rows

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [81, 82, 83, 84, 85, 86, 87, 88, 89, 90]])

In [82]:
arr3d[:,[2,7,4,9]]
#slice specified columns

array([[  3,   8,   5,  10],
       [ 13,  18,  15,  20],
       [ 23,  28,  25,  30],
       [ 33,  38,  35,  40],
       [ 43,  48,  45,  50],
       [ 53,  58,  55,  60],
       [ 63,  68,  65,  70],
       [ 73,  78,  75,  80],
       [ 83,  88,  85,  90],
       [ 93,  98,  95, 100]])

In [84]:
arr3d[[0,1,2,3,4,5,6,7,8,9,],[0,1,2,3,4,5,6,7,8,9]]
#pulls elements in ordered pairs as defined
#first set is [rows] 2nd set is [columns]

array([  1,  12,  23,  34,  45,  56,  67,  78,  89, 100])

In [85]:
arr3d > 30

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [86]:
arr2d*arr2d
#element by element calculation (not matrix calculation)

array([[  25,  100,  225],
       [ 400,  625,  900],
       [1225, 1600, 2025]])

In [87]:
arr3d*arr3d

array([[    1,     4,     9,    16,    25,    36,    49,    64,    81,
          100],
       [  121,   144,   169,   196,   225,   256,   289,   324,   361,
          400],
       [  441,   484,   529,   576,   625,   676,   729,   784,   841,
          900],
       [  961,  1024,  1089,  1156,  1225,  1296,  1369,  1444,  1521,
         1600],
       [ 1681,  1764,  1849,  1936,  2025,  2116,  2209,  2304,  2401,
         2500],
       [ 2601,  2704,  2809,  2916,  3025,  3136,  3249,  3364,  3481,
         3600],
       [ 3721,  3844,  3969,  4096,  4225,  4356,  4489,  4624,  4761,
         4900],
       [ 5041,  5184,  5329,  5476,  5625,  5776,  5929,  6084,  6241,
         6400],
       [ 6561,  6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,
         8100],
       [ 8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
        10000]])

In [88]:
numpy.max(arr2d)

45

In [89]:
numpy.max(arr3d)

100

In [90]:
np.log(arr3d)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
        1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
        2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227],
       [3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
        3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738],
       [3.4339872 , 3.4657359 , 3.49650756, 3.52636052, 3.55534806,
        3.58351894, 3.61091791, 3.63758616, 3.66356165, 3.68887945],
       [3.71357207, 3.73766962, 3.76120012, 3.78418963, 3.80666249,
        3.8286414 , 3.8501476 , 3.87120101, 3.8918203 , 3.91202301],
       [3.93182563, 3.95124372, 3.97029191, 3.98898405, 4.00733319,
        4.02535169, 4.04305127, 4.06044301, 4.07753744, 4.09434456],
       [4.11087386, 4.12713439, 4.14313473, 4.15888308, 4.17438727,
        4.18965474, 4.20469262, 4.21950771, 4.2341065 , 4.24849524],
       [4.26267988, 4.27666612, 4.2904594

In [91]:
A = np.arange(1,5).reshape(2,2)
A

array([[1, 2],
       [3, 4]])

In [92]:
A*A
#element by element (not matrix calc)

array([[ 1,  4],
       [ 9, 16]])

In [93]:
a = np.mat(A)
a*a
#linear algebra matrix calculation; not element by element

matrix([[ 7, 10],
        [15, 22]])

In [95]:
a.T
#transpose

matrix([[1, 3],
        [2, 4]])