In [ ]:
#R matrices

In [1]:
#range of sequential numeric values
1:10

[1]  1  2  3  4  5  6  7  8  9 10

In [2]:
#Assign sequential numeric range to a vector
v <- 1:10
v

[1]  1  2  3  4  5  6  7  8  9 10

In [3]:
#matrix() function
matrix(v)

[,1]
 [1,]  1  
 [2,]  2  
 [3,]  3  
 [4,]  4  
 [5,]  5  
 [6,]  6  
 [7,]  7  
 [8,]  8  
 [9,]  9  
[10,] 10

In [4]:
matrix(v, nrow=2)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [5]:
matrix(v, byrow=FALSE, nrow=2)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [6]:
matrix(v, byrow=TRUE, nrow=2)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4     5  
[2,] 6    7    8    9    10

In [7]:
matrix(1:12, byrow=TRUE, nrow=4)

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12

In [8]:
Lewiston <- c(12,14,18,13,17)
Rocky.Mount <- c(11,19,21,15,18)
Whiteville <- c(14,17,23,11,9)

In [9]:
weights <- c(Lewiston, Rocky.Mount, Whiteville)

In [10]:
weights

[1] 12 14 18 13 17 11 19 21 15 18 14 17 23 11  9

In [13]:
weights.matrix <- matrix(weights, byrow=TRUE, nrow=3)
weights.matrix

[,1] [,2] [,3] [,4] [,5]
[1,] 12   14   18   13   17  
[2,] 11   19   21   15   18  
[3,] 14   17   23   11    9

In [14]:
# Name rows=rownames(), columns=colnames()
days <- c('Mon', 'Tue', 'Wed', 'Thu', 'Fri')
loc.names <- c('Lewiston', 'Rocky Mount', 'Whiteville')

In [15]:
days

[1] "Mon" "Tue" "Wed" "Thu" "Fri"

In [16]:
loc.names

[1] "Lewiston"    "Rocky Mount" "Whiteville"

In [17]:
weights.matrix

[,1] [,2] [,3] [,4] [,5]
[1,] 12   14   18   13   17  
[2,] 11   19   21   15   18  
[3,] 14   17   23   11    9

In [18]:
colnames(weights.matrix) <- days
rownames(weights.matrix) <- loc.names

In [19]:
weights.matrix

Mon Tue Wed Thu Fri
Lewiston    12  14  18  13  17 
Rocky Mount 11  19  21  15  18 
Whiteville  14  17  23  11   9

In [20]:
#set up a matrix with 5 rows and 10 columns
mat <- matrix(1:50, byrow=TRUE, nrow=5)
mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  1    2    3    4    5    6    7    8    9   10   
[2,] 11   12   13   14   15   16   17   18   19   20   
[3,] 21   22   23   24   25   26   27   28   29   30   
[4,] 31   32   33   34   35   36   37   38   39   40   
[5,] 41   42   43   44   45   46   47   48   49   50

In [21]:
2*mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  2    4    6    8   10   12   14   16   18    20  
[2,] 22   24   26   28   30   32   34   36   38    40  
[3,] 42   44   46   48   50   52   54   56   58    60  
[4,] 62   64   66   68   70   72   74   76   78    80  
[5,] 82   84   86   88   90   92   94   96   98   100

In [22]:
1/mat

[,1]       [,2]       [,3]       [,4]       [,5]       [,6]      
[1,] 1.00000000 0.50000000 0.33333333 0.25000000 0.20000000 0.16666667
[2,] 0.09090909 0.08333333 0.07692308 0.07142857 0.06666667 0.06250000
[3,] 0.04761905 0.04545455 0.04347826 0.04166667 0.04000000 0.03846154
[4,] 0.03225806 0.03125000 0.03030303 0.02941176 0.02857143 0.02777778
[5,] 0.02439024 0.02380952 0.02325581 0.02272727 0.02222222 0.02173913
     [,7]       [,8]       [,9]       [,10]     
[1,] 0.14285714 0.12500000 0.11111111 0.10000000
[2,] 0.05882353 0.05555556 0.05263158 0.05000000
[3,] 0.03703704 0.03571429 0.03448276 0.03333333
[4,] 0.02702703 0.02631579 0.02564103 0.02500000
[5,] 0.02127660 0.02083333 0.02040816 0.02000000

In [23]:
mat**2

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]    1    4    9   16   25   36   49   64   81  100 
[2,]  121  144  169  196  225  256  289  324  361  400 
[3,]  441  484  529  576  625  676  729  784  841  900 
[4,]  961 1024 1089 1156 1225 1296 1369 1444 1521 1600 
[5,] 1681 1764 1849 1936 2025 2116 2209 2304 2401 2500

In [26]:
mat2 <- matrix(1:9, nrow=3)
mat2

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [27]:
#element by element multiplication
mat2*mat2

[,1] [,2] [,3]
[1,] 1    16   49  
[2,] 4    25   64  
[3,] 9    36   81

In [28]:
# %*% uses actual matrix algebra multiplication
mat2 %*% mat2

[,1] [,2] [,3]
[1,] 30   66   102 
[2,] 36   81   126 
[3,] 42   96   150

In [29]:
weights.matrix

Mon Tue Wed Thu Fri
Lewiston    12  14  18  13  17 
Rocky Mount 11  19  21  15  18 
Whiteville  14  17  23  11   9

In [30]:
#calc across columns using colSums()
colSums(weights.matrix)

Mon Tue Wed Thu Fri 
 37  50  62  39  44

In [31]:
rowSums(weights.matrix)

Lewiston Rocky Mount  Whiteville 
         74          84          74

In [32]:
colMeans(weights.matrix)

Mon      Tue      Wed      Thu      Fri 
12.33333 16.66667 20.66667 13.00000 14.66667

In [33]:
rowMeans(weights.matrix)

Lewiston Rocky Mount  Whiteville 
       14.8        16.8        14.8

In [35]:
#Add the Clayton location onto weights.matrix
Clayton <- c(17, 23, 15, 19, 13)

In [36]:
Clayton

[1] 17 23 15 19 13

In [37]:
#add Clayton to weights.matrix
#cbind() for column or rbind() for row
ncsu.matrix <- rbind(weights.matrix, Clayton)

In [38]:
ncsu.matrix

Mon Tue Wed Thu Fri
Lewiston    12  14  18  13  17 
Rocky Mount 11  19  21  15  18 
Whiteville  14  17  23  11   9 
Clayton     17  23  15  19  13

In [39]:
loc.means <- rowMeans(ncsu.matrix)
loc.means

Lewiston Rocky Mount  Whiteville     Clayton 
       14.8        16.8        14.8        17.4

In [40]:
ncsu.matrix <- cbind(ncsu.matrix, loc.means)
ncsu.matrix

Mon Tue Wed Thu Fri loc.means
Lewiston    12  14  18  13  17  14.8     
Rocky Mount 11  19  21  15  18  16.8     
Whiteville  14  17  23  11   9  14.8     
Clayton     17  23  15  19  13  17.4

In [41]:
short <- c(2,18,12)
long <- c(12,11,10,9,8)

In [43]:
ncsu2.matrix <- ncsu.matrix
cbind(ncsu2.matrix, short)

Warning message in cbind(ncsu2.matrix, short):
"number of rows of result is not a multiple of vector length (arg 2)"

Mon Tue Wed Thu Fri loc.means short
Lewiston    12  14  18  13  17  14.8       2   
Rocky Mount 11  19  21  15  18  16.8      18   
Whiteville  14  17  23  11   9  14.8      12   
Clayton     17  23  15  19  13  17.4       2

In [44]:
cbind(ncsu2.matrix,long)

Warning message in cbind(ncsu2.matrix, long):
"number of rows of result is not a multiple of vector length (arg 2)"

Mon Tue Wed Thu Fri loc.means long
Lewiston    12  14  18  13  17  14.8      12  
Rocky Mount 11  19  21  15  18  16.8      11  
Whiteville  14  17  23  11   9  14.8      10  
Clayton     17  23  15  19  13  17.4       9

In [45]:
#example.matrix(row,col)
mat <- matrix(1:50, byrow=TRUE, nrow=5)
mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  1    2    3    4    5    6    7    8    9   10   
[2,] 11   12   13   14   15   16   17   18   19   20   
[3,] 21   22   23   24   25   26   27   28   29   30   
[4,] 31   32   33   34   35   36   37   38   39   40   
[5,] 41   42   43   44   45   46   47   48   49   50

In [49]:
#before comma in index gives row
#after comma in index gives column
#column 1 pulled here
mat[,1]

[1]  1 11 21 31 41

In [48]:
mat[1:3,]

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  1    2    3    4    5    6    7    8    9   10   
[2,] 11   12   13   14   15   16   17   18   19   20   
[3,] 21   22   23   24   25   26   27   28   29   30

In [50]:
mat[1:2,1:3]

[,1] [,2] [,3]
[1,]  1    2    3  
[2,] 11   12   13

In [51]:
mat[2,5:6]

[1] 15 16

In [52]:
#factor and categorical matrices
#factor() function
#ex; one-way anova; when import categorical data need to define as a factor
#example P=peanut, M=maize, S=soybean, C=cotton
crop <- c('P', 'P', 'M', 'C', 'S', 'S', 'M', 'C', 'P', 'C')
id <- c(1,2,3,4,5,6,7,8,9,10)

In [53]:
factor.crop <- factor(crop)

In [54]:
#levels picks out levels/groups of your factor/categorical data
#crop is nominal variable (does not have ordinal levels)
factor.crop

[1] P P M C S S M C P C
Levels: C M P S

In [55]:
#ordinal data has defined order of levels (ex heat)
#ordered=TRUE
#levels = c('The order')
ord.cat <- c('cold', 'med', 'hot')

In [59]:
temps <- c('cold', 'hot', 'hot', 'med', 'cold', 'hot', 'med', 'cold', 'med')
fact.temps <- factor(temps, ordered=TRUE, levels=c('cold','med','hot'))

In [60]:
fact.temps

[1] cold hot  hot  med  cold hot  med  cold med 
Levels: cold < med < hot

In [61]:
temps <- c('cold', 'hot', 'hot', 'med', 'cold', 'hot', 'med', 'cold', 'med')
fact.temps1 <- factor(temps, ordered=TRUE, levels=ord.cat) #since we already defined order as ord.cat, can assign using that

In [62]:
fact.temps1

[1] cold hot  hot  med  cold hot  med  cold med 
Levels: cold < med < hot

In [63]:
summary(temps)

   Length     Class      Mode 
        9 character character 

In [64]:
summary(fact.temps)

cold  med  hot 
   3    3    3