![](Logo.png)

# <font color='red'>Week 3 - R Matrices Exercise</font>

This week focused on the R matrix data structure; creating matrices, indexing and selecting elements and matrix operations. Answer the questions regarding R matrices

#### Create two vectors (A and B), where A is (1,2,3) and B is (4,5,6). With these vectors, use the cbind() or rbind() function to create a 2 x 3 matrix from the vectors. Based on the output, determine the appropriate function to use.

In [1]:
A <- c(1:3)
B <- c(4:6)
AB <- rbind(A,B)
AB

[,1] [,2] [,3]
A 1    2    3   
B 4    5    6

A matrix: 2 × 3 of type dbl
<br>A	1	2	3
<br>B	4	5	6


#### Create a 3 x 3 matrix consisting of the numbers 1-9. Create this matrix using the shortcut 1:9 and by specifying the nrow argument in the matrix() function call. Assign this matrix to the variable *mat

In [7]:
mat <- matrix(1:9, byrow=FALSE, nrow=3)
mat

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

A matrix: 3 × 3 of type int
<br>1	4	7
<br>2	5	8
<br>3	6	9

#### Confirm that *mat* is a matrix

In [10]:
class(mat) == 'matrix'

[1] TRUE

TRUE

#### Create a 5 x 5 matrix consisting of the numbers 1-25 and assign it to the variable *mat2*. The top row should be the numbers 1-5

In [12]:
mat2 <- matrix(1:25, byrow=TRUE, nrow=5)
mat2

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

A matrix: 5 × 5 of type int
<br>1	2	3	4	5
<br>6	7	8	9	10
<br>11	12	13	14	15
<br>16	17	18	19	20
<br>21	22	23	24	25

#### Use index notation to grab a subsection of *mat2* that replicates the output

In [ ]:
# WRITE CODE HERE

In [14]:
mat2[2:3,2:3]

[,1] [,2]
[1,]  7    8  
[2,] 12   13

A matrix: 2 × 2 of type int
<br>7	8
<br>12	13

#### Use index notation to grab a subsection of *mat2* that replicates the output

In [15]:
mat2[4:5,4:5]

[,1] [,2]
[1,] 19   20  
[2,] 24   25

A matrix: 2 × 2 of type int
<br>19	20
<br>24	25

#### What is the sum of all of the elements of *mat2*?

In [19]:
sum(mat2)

[1] 325

325

#### Find out how to use the Built-in R Function runif() to create a 4 x 5 matrix consisting of 20 random numbers

In [20]:
# For help, use help(function) to show the usage
help(runif)

In [21]:
randommat <- matrix(runif(20, min = 0, max=100), byrow=TRUE, nrow=4)
randommat

[,1]     [,2]      [,3]     [,4]      [,5]    
[1,] 79.03838  4.801037  3.35826 95.408583 43.71047
[2,] 81.50652 50.853551 99.20377  7.652248 80.97372
[3,] 46.35766  9.536375 40.83064 50.580005 72.81640
[4,] 92.70826 98.449268 43.16699 99.295264 29.30832

A matrix: 4 × 5 of type dbl
<br>69.80866	30.89378	48.11989	66.671924	57.627178
<br>84.47939	22.60094	42.50644	5.705361	99.697690
<br>34.14663	5.36340	14.70970	73.329675	78.732104
<br>90.33467	15.86248	82.81758	86.678541	6.105884


For other useful random number generators, reference the [R documentation](https://www.rdocumentation.org/packages/pracma/versions/1.9.9/topics/rand) and source help() for usage